namespace: vampio
forklift:
  persistence:
    database:
      sql:
        database: vamp-${namespace}
        table: ${namespace}
      type: mysql
    key-value-store:
      base-path: /secret/vamp/${namespace}
      type: vault
    transformers:
      classes: []
  metadata:
    namespace:
      title: organization
