version: 2  # CircleCI version
jobs:
  deploy-production:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - run:
          commmand: ./authenticate-gcloud.sh
      - run:
          command: ./deploy.sh
workflows:
  version: 2
  deploy-production:
    jobs:
      - deploy-production:
          filters:
            branches:
              only: master
