version: 2.1
defaults: &defaults
  docker:
    - image: vampio/kmt:circleci-0.2.0
orbs:
  gcp-cli: circleci/gcp-cli@1.1.0
  kubernetes: circleci/kubernetes@0.1.0
jobs:
  create-env:
    <<: *defaults
    steps:
      - checkout
      - gcp-cli/install
      - gcp-cli/initialize
      - kubernetes/install
      - run:
          name: Connect to cluster
          command: |
            gcloud --quiet container clusters get-credentials $GOOGLE_CLUSTER_NAME
            kubectl get namespaces
      - run:
          name: Create org
          command: |
            organization=tutorial5
            if [ ! "$(forklift list organizations | awk -v org=$organization '$2 == org {print $2}')" = $organization ]; then
              echo "no match"
              forklift create organization $organization --configuration ./org-$organization.yaml --config forklift-config.yaml
            fi

workflows:
  version: 2
  create-env-deploy-gateways:
    jobs:
      - create-env
