version: 2
defaults: &defaults
  docker:
    - image: google/cloud-sdk:latest
jobs:
  create-env:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: workspace
      - run:
          name: Install utils
          command: |
            apt-get update
            apt-get install jq
      - run:
          name: Connect to cluster
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > gcloud-service-key.json
            set -x
            gcloud auth activate-service-account --key-file gcloud-service-key.json
            gcloud --quiet config set project $GOOGLE_PROJECT_ID
            gcloud --quiet config set compute/zone $GOOGLE_COMPUTE_ZONE
            gcloud --quiet container clusters get-credentials $GOOGLE_CLUSTER_NAME
            kubectl get namespaces
      - run:
          name: Create tenant environment
          command: |
            KUBERNETES_NAMESPACE=default
            LIFTER_POD=$(kubectl get pods -l app=lifter -o go-template --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}')
            kubectl --namespace ${KUBERNETES_NAMESPACE} exec ${LIFTER_POD} -- curl -s -o /dev/null -X PUT -H "Content-Type: application/json" -d '{}' http://127.0.0.1:8081/api/namespaces/vampio-organization-cctest
            kubectl --namespace ${KUBERNETES_NAMESPACE} exec ${LIFTER_POD} -- curl -s -o /dev/null -X POST -H "Content-Type: application/json" -d '{"artifacts":{"/usr/local/vamp/artifacts/breeds/quantification.yml":true,"/usr/local/vamp/artifacts/workflows/quantification.yml":true,"/usr/local/vamp/artifacts/breeds/vamp-workflow-javascript.yml":true},"persistence":true,"pulse":true,"key_value":true,"namespace":true}' http://127.0.0.1:8081/api/namespaces/vampio-organization-cctest/setup
      - run:
          name: Restart Vamp
          command: |
            KUBERNETES_NAMESPACE=default
            kubectl --namespace ${KUBERNETES_NAMESPACE} delete pods -l app=vamp
            kubectl --namespace ${KUBERNETES_NAMESPACE} rollout status deployment.v1beta1.apps/vamp
      - run:
          name: Deploy VGAs
          command: |
            KUBERNETES_NAMESPACE=default
            LIFTER_POD=$(kubectl get pods -l app=lifter -o go-template --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}')
            kubectl --namespace ${KUBERNETES_NAMESPACE} exec ${LIFTER_POD} -- curl -s -X GET -o /vga.yml http://127.0.0.1:8081/api/vga
            kubectl --namespace ${KUBERNETES_NAMESPACE} exec ${LIFTER_POD} -- curl -s -o /dev/null -X POST --data-binary "@/vga.yml" http://127.0.0.1:8081/api/namespaces/vampio-organization-cctest/vga

  deploy-gateways:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run:
          name: Install Vamp CLI
          command: |
            npm install vamp-cli-ee -g
      - run:
          name: Connect to Vamp
          command: |
            vamp list gateways
            ls
      
workflows:
  version: 2
  create-env-deploy-gateways:
    jobs:
      - deploy-gateways:
          filters:
            branches:
              only: master
