version: 2.1
defaults: &defaults
  docker:
    - image: vampio/kmt:circleci-latest
orbs:
  gcp-cli: circleci/gcp-cli@1.1.0
  kubernetes: circleci/kubernetes@0.1.0
jobs:
  create-env:
    <<: *defaults
    steps:
      - checkout
      - gcp-cli/install
      - gcp-cli/initialize
      - kubernetes/install
      - run:
          name: Connect to cluster
          command: |
            gcloud --quiet container clusters get-credentials $GOOGLE_CLUSTER_NAME
            kubectl get namespaces
      - run:
          name: Set forklift config
          command: |
            mkdir ~/.forklift
            cp forklift-config.yaml ~/.forklift/config.yaml
      - run:
          name: Create org and env
          command: |
            organization=tutorial5
            if [ ! "$(forklift list organizations | awk -v org=$organization '$2 == org {print $2}')" = $organization ]; then
              echo "Creating organization: $organization"
              forklift create organization $organization --configuration org-$organization.yaml
            fi
            environment=eu
            if [ ! "$(forklift list environments --organization $organization | awk -v env=$environment '$2 == env {print $2}')" = $environment ]; then
              echo "Creating environment: $environment"
            fi
            forklift list environments --organization $organization 

workflows:
  version: 2
  create-env-deploy-gateways:
    jobs:
      - create-env
